version: '3.4'

services:
  todolist:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGO_DB_URL: mongodb://mongodb:27017
      LOG_LEVEL: debug
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    command: --quiet

volumes:
  mongodb-data: